### ISSUE TITLE
Orbterm crashes on window resize

### ISSUE THREAD

**Issue by xTibor** [redox-os/orbterm#1]
**Reproduction**:
1. Login as `user`, open `orbterm`
2. Execute `cat rand:`
3. Resize the window vertically

**Expected behavior**:
Not to crash.

**Actual behavior**:
The app crashes and the system produces the following error messages:
```
launcher: 47 exited with signal: 11
launcher: reaping zombie 48: signal 4
```
and
```
Page fault: 06:00000100001B1F30 at 23:000000000040D0B0
TRACE: FFFFFF400014B0C0
  FFFFFF400014B0C0: FFFFFF00001B6D41
    FFFFFF00001B6C80+00C1
  FFFFFF400014B150: FFFFFF00001B6C71
  00000180000FE970: 000000000040F816
  00000180000FFDE0: 0000000000422CDC
  00000180000FFDF0: 0000000000422734
  00000180000FFE80: 00000000004001F5
 0000008000000018: EMPTY RETURN
SIGNAL 11, CPU 0, PID ContextId(47)
NAME file:/ui/bin/orbterm
Invalid opcode fault at 23:000000000048BD96
TRACE: FFFFFF40001AB0F8
  FFFFFF40001AB0F8: FFFFFF00001B6689
    FFFFFF00001B65F0+0099
  FFFFFF40001AB158: FFFFFF00001B65E1
  00000180000FDF70: 000000000048F7CE
  00000180000FDFA0: 000000000048F778
  00000180000FE010: 000000000049D1B7
  00000180000FE070: 0000000000410BAA
  00000180000FE0F0: 000000000041D4FA
  00000180000FE4C0: 00000000004694CA
  00000180000FE680: 0000000000473A1F
  00000180000FFDB0: 0000000000475C1C
  00000180000FFE10: 000000000047FDB7
  00000180000FFE80: 00000000004001F5
 0000008000000018: EMPTY RETURN
SIGNAL 4, CPU 0, PID ContextId(48)
NAME file:/bin/ion
```

**Build information**:
`rustc -V`: rustc 1.19.0-nightly (04145943a 2017-06-19)
`git rev-parse HEAD`: 87ed4e1ec55e67b5c1cc17d83f1efd745ccd3e07

**Misc**:
Horizontal resizing doesn't crash the app.

**Comment by xTibor** [comment]
I spent some time on this issue and managed to narrow it down a bit. The app crashes on this line: https://github.com/redox-os/orbterm/blob/bd13d06f1c41dbfeb053825162b4281c472c0917/src/handle.rs#L29

So the problem might lurk in `Console::input` somewhere.

**Comment by xTibor** [comment]
Found the problem: Off by one errors in the cursor gfx inverter code. They are causing out of bounds memory accesses.

I'll make a pull request to fix them tomorrow.

**Comment by jackpot51** [comment]
Thanks for this @xTibor !
