### ISSUE TITLE
Orbterm crashes after window resize

### ISSUE THREAD

**Issue by xTibor** [redox-os/orbterm#5]
**Reproduction**:
1. Move the cursor halfways through the window
2. Resize the window until the cursor falls out of the window (https://i.imgur.com/MU32bxk.png)
3. Press enter
4. Segfault

**Build information:**
`rustc -V`: `rustc 1.22.0-nightly (4c053db23 2017-10-22)`
`git rev-parse HEAD`: https://github.com/redox-os/orbterm/commit/b2953da6f0e626c29f8b6db805225e12dee68e05

**Misc**:
Segfaults both on Linux and Redox.

**Comment by jackpot51** [comment]
This is fixed now.
